# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'encode_decode.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from base64 import b64encode, b64decode

class Ui_Base64(object):
    def setupUi(self, Base64):
        Base64.setObjectName("Base64")
        Base64.resize(573, 858)
        Base64.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(Base64)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 30, 331, 61))
        self.label.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 25pt \"hooge 05_55\";")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 120, 481, 51))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 18pt \"Bahnschrift Condensed\";")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 250, 101, 21))
        self.label_2.setStyleSheet("color: rgb(85, 170, 0);\n"
"font: 14pt \"MS Sans Serif\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 380, 331, 61))
        self.label_3.setStyleSheet("color: rgb(0, 170, 0);\n"
"color: rgb(255, 0, 0);\n"
"font: 25pt \"hooge 05_55\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 480, 481, 51))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 18pt \"Bahnschrift Condensed\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 620, 101, 21))
        self.label_4.setStyleSheet("color: rgb(85, 170, 0);\n"
"color: rgb(255, 0, 0);\n"
"font: 14pt \"MS Sans Serif\";")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 190, 121, 41))
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 0);\n"
"font: 57 10pt \"Dubai Medium\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 550, 121, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 57 10pt \"Dubai Medium\";\n"
"color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 300, 481, 51))
        self.lineEdit_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(85, 170, 0);\n"
"font: 75 14pt \"Carlito\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(50, 670, 481, 51))
        self.lineEdit_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);\n"
"font: 75 14pt \"Carlito\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 750, 121, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 10pt \"Dubai Medium\";")
        self.pushButton_3.setObjectName("pushButton_3")
        Base64.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Base64)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 573, 26))
        self.menubar.setObjectName("menubar")
        Base64.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Base64)
        self.statusbar.setObjectName("statusbar")
        Base64.setStatusBar(self.statusbar)

        self.retranslateUi(Base64)
        self.pushButton_3.clicked.connect(self.lineEdit_4.clear)
        self.pushButton_3.clicked.connect(self.lineEdit_3.clear)
        self.pushButton_3.clicked.connect(self.lineEdit_2.clear)
        self.pushButton_3.clicked.connect(self.lineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(Base64)

    def retranslateUi(self, Base64):
        _translate = QtCore.QCoreApplication.translate
        Base64.setWindowTitle(_translate("Base64", "Base64"))
        self.label.setText(_translate("Base64", "Encode Base64"))
        self.label_2.setText(_translate("Base64", "encoded"))
        self.label_3.setText(_translate("Base64", "decode Base64"))
        self.label_4.setText(_translate("Base64", "decoded"))
        self.pushButton.setText(_translate("Base64", "Confirm"))
        self.pushButton_2.setText(_translate("Base64", "Confirm"))
        self.lineEdit_2.setWhatsThis(_translate("Base64", "<html><head/><body><p>text</p></body></html>"))
        self.lineEdit_4.setWhatsThis(_translate("Base64", "<html><head/><body><p>text</p></body></html>"))
        self.pushButton_3.setText(_translate("Base64", "Clear"))
        self.pushButton.clicked.connect(self.encode_base64)
        self.pushButton_2.clicked.connect(self.decode_base64)
        
        
    def encode_base64(self):
        text = str(self.lineEdit.text()).encode("utf-8","ascii")
        text_encode = b64encode(text)
        decode_for_use = text_encode.decode("utf-8","ascii")
        self.lineEdit_2.setText(str(decode_for_use))
    
    def decode_base64(self):
        text = str(self.lineEdit_3.text()).encode("utf-8","ascii")
        text_encode = b64decode(text)
        decode_for_use = text_encode.decode("utf-8","ascii")
        self.lineEdit_4.setText(str(decode_for_use))
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Base64()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())